  
name: Laravel Continue Integration

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone the repo
      uses: actions/checkout@v1
      
    - name: Composer install
      uses: docker://composer:1.9.1
      with:
        args: install

    - name: PHPUnit testing
      uses: docker://php:7.3
      with:
        args: |
          php vendor/bin/phpunit
     
    - name: node install
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run production
    
    - name: Change file permission
      run: |
        sudo find . -type f -exec chmod 664 {} + 
        sudo find . -type d -exec chmod 775 {} + 
        sudo chown -R www-data:www-data .
        ls -alh
        
    - name: Deploy to server without git & .env
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      with:
        flags: '-avz --exclude=".git*" --exclude .env'
        options: ''
        ssh_options: '-p ${{secrets.SSH_PORT}}'
        src: '.'
        dest: '${{secrets.SSH_USER}}@${{secrets.SSH_SERVER}}:/var/www/github_action/'
      
